### ISSUE TITLE
error compiling examples in sample folder

### ISSUE THREAD

**Issue by francescoagati** [silexlabs/Cocktail#423]
Hi,
while try to compile samples in examples folder i get this error.
```
/usr/lib/haxe/lib/cocktail/1,0,0-beta,5/cocktail/core/parser/DOMParser.hx:104: characters 12-26 : Unmatched patterns: Document | ProcessingInstruction | DocType | Comment | CData | Element
/usr/lib/haxe/lib/cocktail/1,0,0-beta,5/cocktail/core/parser/DOMParser.hx:83: characters 10-22 : Unmatched patterns: Document | ProcessingInstruction | DocType | CData
```
i have do 
```
cd 01-HelloWorld/
cd build
haxe compile-swf.hxml 
```

haxe version 3.2
cocktail version 1.0.0-beta.5

**Comment by markknol** [comment]
Looks like someone forgot to add the `default` to each switch-statement.

**Comment by yanhick** [comment]
Yep that's the issue, I hadn't built for haxe 3.2.0, and it looks like the Xml object is an enum now so it needs a default case.

I pushed a fix here:
https://github.com/silexlabs/Cocktail/tree/fix-xml-for-3.2.0

**Comment by francescoagati** [comment]
thanks now work on haxe 3.2

**Comment by webryan** [comment]
`
C:\HaxeToolkit\haxe\lib\cocktail\1,0,0-beta,5\samples\04-Dom\build>haxe compile-
swf.hxml
C:\HaxeToolkit\haxe\lib\cocktail/1,0,0-beta,5/cocktail/core/parser/DOMParser.hx:
104: characters 12-26 : Unmatched patterns: Document | ProcessingInstruction | D
ocType | Comment | CData | Element
C:\HaxeToolkit\haxe\lib\cocktail/1,0,0-beta,5/cocktail/core/parser/DOMParser.hx:
83: characters 10-22 : Unmatched patterns: Document | ProcessingInstruction | Do
cType | CData
`

I still have this problem on cocktail 1,0,0-beta,5.  Any solution?

@yanhick  Haxe Compiler 3.2.1 - (C)2005-2015 Haxe Foundation

**Comment by frankhdz** [comment]
Well this sucks.. there is no fix because the linked repo is not there
